version: '3'
services:
  app:
    build:
      context: .
    container_name: verileum-task-api
    command: npm run typeorm:run
    command: npm run start
    depends_on:
      - database
    restart: always
    environment: 
      - PORT=4000
      - APP_NAME='Verileum API'
      - APP_HOST=localhost
      - DATABASE_TYPE=mysql
      - JWT_AUTH_SECRET=secret

      - DATABASE_HOST=database
      - DATABASE_NAME=verileum
      - DATABASE_USERNAME=root
      - DATABASE_PORT=3306
      - DATABASE_PASSWORD=password


    ports:
      - 4000:4000
  database:
    image: mysql:5.7
    restart: always
    platform: linux/x86_64
    environment:
      MYSQL_DATABASE: 'verileum'
      # So you don't have to use root, but you can if you like
      
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql

volumes:
  my-db: 
